import { m } from "#shared/internationalization/messages.js"

export const technologies = [
  { description: m.tech_astro, label: "astro", name: "Astro" },
  { description: m.tech_better_auth, label: "better-auth", name: "Better Auth" },
  { description: m.tech_bun, label: "bun", name: "Bun" },
  { description: m.tech_docker, label: "docker", name: "Docker" },
  { description: m.tech_drizzle, label: "drizzle", name: "Drizzle" },
  { description: m.tech_expo, label: "expo", name: "Expo" },
  { description: m.tech_fumadocs, label: "fumadocs", name: "Fumadocs" },
  { description: m.tech_hono, label: "hono", name: "Hono" },
  { description: m.tech_nextjs, label: "nextjs", name: "Next.js" },
  { description: m.tech_postgres, label: "postgres", name: "Postgres" },
  { description: m.tech_react_router, label: "react-router", name: "React Router" },
  { description: m.tech_react, label: "react", name: "React" },
  { description: m.tech_sqlite, label: "sqlite", name: "SQLite" },
  { description: m.tech_tailwindcss, label: "tailwindcss", name: "Tailwind" },
  { description: m.tech_tanstack_query, label: "tanstack-query", name: "TanStack Query" },
  { description: m.tech_tanstack_router, label: "tanstack-router", name: "TanStack Router" },
  { description: m.tech_trpc, label: "trpc", name: "TRPC" },
  { description: m.tech_typescript, label: "typescript", name: "TypeScript" },
  { description: m.tech_unistyles, label: "unistyles", name: "Unistyles" },
  { description: m.tech_vite, label: "vite", name: "Vite" },
  { description: m.tech_zod, label: "zod", name: "Zod" },
] as const
