export const technologies = [
  { label: "astro", name: "Astro" },
  { label: "better-auth", name: "Better Auth" },
  { label: "bun", name: "Bun" },
  { label: "docker", name: "Docker" },
  { label: "drizzle", name: "Drizzle" },
  { label: "expo", name: "Expo" },
  { label: "fumadocs", name: "Fumadocs" },
  { label: "hono", name: "Hono" },
  { label: "nextjs", name: "Next.js" },
  { label: "postgres", name: "Postgres" },
  { label: "react-router", name: "React Router" },
  { label: "react", name: "React" },
  { label: "sqlite", name: "SQLite" },
  { label: "tailwindcss", name: "Tailwind" },
  { label: "tanstack-query", name: "TanStack Query" },
  { label: "tanstack-router", name: "TanStack Router" },
  { label: "trpc", name: "TRPC" },
  { label: "typescript", name: "TypeScript" },
  { label: "unistyles", name: "Unistyles" },
  { label: "vite", name: "Vite" },
  { label: "zod", name: "Zod" },
] as const
